allAIs = dumbAI:dumbAI mediumAI:mediumAI smartAI:smartAI;

dumbAI = 'Short' '{' singleDumbAI:singleDumbAI '}';
mediumAI = 'Int' '{' singleMediumAI:singleMediumAI '}';
smartAI = 'Double' '{' singleSmartAI:singleSmartAI '}';

singleDumbAI = formationDef:dumbFormationDef movementDef:dumbMovementDef
               targetingDef:dumbTargetingDef;

singleMediumAI = formationDef:mediumFormationDef movementDef:mediumMovementDef
                 targetingDef:mediumTargetingDef;

singleSmartAI = formationDef:smartFormationDef movementDef:smartMovementDef
                targetingDef:smartTargetingDef;

dumbFormationDef = 'Formation' '{' [formationRules:dumbFormationRules] '}';

mediumFormationDef = 'Formation' '{' [formationRules:mediumFormationRules] '}';

smartFormationDef = 'Formation' '{' [formationRules:smartFormationRules] '}';

dumbMovementDef = 'Movement' '{' [movementRules:dumbMovementRules] '}';

mediumMovementDef = 'Movement' '{' [movementRules:mediumMovementRules] '}';

smartMovementDef = 'Movement' '{' [movementRules:smartMovementRules] '}';

dumbTargetingDef = 'Targeting' '{' [targetingRules:dumbTargetingRules] '}';

mediumTargetingDef = 'Targeting' '{' [targetingRules:mediumTargetingRules] '}';

smartTargetingDef = 'Targeting' '{' [targetingRules:smartTargetingRules] '}';

dumbFormationRules = [extraFormationRules:extraDumbFormationRules] 'default:'
                     defaultFormation:dumbFormation | extraFormationRules:
                     extraDumbFormationRules;

mediumFormationRules = [extraFormationRules:extraMediumFormationRules] 'default:'
                       defaultFormation:mediumFormation | extraFormationRules:
                       extraMediumFormationRules;

smartFormationRules = [extraFormationRules:extraSmartFormationRules] 'default:'
                      defaultFormation:smartFormation | extraFormationRules:
                      extraSmartFormationRules;

dumbMovementRules = [extraMovementRules:extraDumbMovementRules] 'default:'
                    defaultMovement:dumbMovement | extraMovementRules:
                    extraDumbMovementRules;

mediumMovementRules = [extraMovementRules:extraMediumMovementRules] 'default:'
                    defaultMovement:mediumMovement | extraMovementRules:
                    extraMediumMovementRules;

smartMovementRules = [extraSmartMovementRules:extraSmartMovementRules] 'default:'
                     defaultMovement:smartMovement | extraMovementRules:
                     extraSmartMovementRules;

dumbTargetingRules = [extraTargetingRules:extraDumbTargetingRules] 'default:'
                     defaultTargeting:dumbTargeting | extraTargetingRules:
                     extraDumbTargetingRules;

mediumTargetingRules = [extraTargetingRules:extraMediumTargetingRules] 'default:'
                       defaultTargeting:mediumTargeting | extraTargetingRules:
                       extraMediumTargetingRules;

smartTargetingRules = [extraTargetingRules:extraSmartTargetingRules] 'default:'
                      defaultTargeting:smartTargeting | extraTargetingRules:
                      extraSmartTargetingRules;

extraDumbFormationRules = {formationRule:dumbFormationRule}+;

extraMediumFormationRules = {formationRule:mediumFormationRule}+;

extraSmartFormationRules = {formationRule:smartFormationRule}+;

extraDumbMovementRules = {movementRule:dumbMovementRule}+;

extraMediumMovementRules = {movementRule:mediumMovementRule}+;

extraSmartMovementRules = {movementRule:smartMovementRule}+;

extraDumbTargetingRules = {targetingRule:dumbTargetingRule}+;

extraMediumTargetingRules = {targetingRule:mediumTargetingRule}+;

extraSmartTargetingRules = {targetingRule:smartTargetingRule}+;

dumbFormationRule = conditional:conditional ':' formation:dumbFormation;

mediumFormationRule = conditional:conditional ':' formation:mediumFormation;

smartFormationRule = conditional:conditional ':' formation:smartFormation;

dumbMovementRule = conditional:conditional ':' movement:dumbMovement;

mediumMovementRule = conditional:conditional ':' movement:mediumMovement;

smartMovementRule = conditional:conditional ':' movement:smartMovement;

dumbTargetingRule = conditional:conditional ':' targeting:dumbTargeting;

mediumTargetingRule = conditional:conditional ':' targeting:mediumTargeting;

smartTargetingRule = conditional:conditional ':' targeting:smartTargeting;

dumbFormation = formation:formation;

mediumFormation = formation:formation;

smartFormation = formation:formation;

formation = 'tight formation' | 'loose formation' | 'isolation';

dumbMovement = movement:movement;

mediumMovement = movement:movement;

smartMovement = movement:movement;

movement = 'move toward' | 'move away' | 'hold ground';

dumbTargeting = targeting:targeting;

mediumTargeting = targeting:targeting;

smartTargeting = targeting:targeting;

targeting = 'target closest' | 'target farthest' | 'target lowest health'
            | 'target smartest' | 'target highest range';

conditional = 'if' condition:condition [extraConditions];

extraConditions = 'and' condition:condition [extraConditions];

condition = enemyProximity:enemyProximity | allyProximity:allyProximity |
            myHealth:myHealth | enemyIQ:enemyIQ | enemyHealth:enemyHealth |
            enemyRange:enemyRange;

enemyProximity = 'there are' number:number 'enemies' proximity:proximity;

allyProximity = 'there are' number:number 'allies' proximity:proximity;

proximity = 'adjacent' | 'close' | 'around';

myHealth = 'my health' comparison:comparison number:number;

enemyIQ = 'a nearby enemy has IQ' comparison:comparison number:number;

enemyHealth = 'a nearby enemy has health' comparison:comparison number:number;

enemyRange = 'a nearby enemy has range' comparison:comparison number:number;

comparison = '<' | '>';

number = /[0-9]+/;
