#!/usr/bin/env python
# -*- coding: utf-8 -*-

# CAVEAT UTILITOR
#
# This file was automatically generated by Grako.
#
#    https://pypi.python.org/pypi/grako/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.


from __future__ import print_function, division, absolute_import, unicode_literals
from grako.parsing import graken, Parser


__version__ = (2014, 12, 6, 23, 6, 53, 5)

__all__ = [
    'SingleAIGrammarParser',
    'SingleAIGrammarSemantics',
    'main'
]


class SingleAIGrammarParser(Parser):
    def __init__(self, whitespace=None, nameguard=True, **kwargs):
        super(SingleAIGrammarParser, self).__init__(
            whitespace=whitespace,
            nameguard=nameguard,
            **kwargs
        )

    @graken()
    def _allAIs_(self):
        self._dumbAI_()
        self.ast['dumbAI'] = self.last_node
        self._mediumAI_()
        self.ast['mediumAI'] = self.last_node
        self._smartAI_()
        self.ast['smartAI'] = self.last_node

        self.ast._define(
            ['dumbAI', 'mediumAI', 'smartAI'],
            []
        )

    @graken()
    def _dumbAI_(self):
        self._token('Short')
        self._token('{')
        self._singleDumbAI_()
        self.ast['singleDumbAI'] = self.last_node
        self._token('}')

        self.ast._define(
            ['singleDumbAI'],
            []
        )

    @graken()
    def _mediumAI_(self):
        self._token('Int')
        self._token('{')
        self._singleMediumAI_()
        self.ast['singleMediumAI'] = self.last_node
        self._token('}')

        self.ast._define(
            ['singleMediumAI'],
            []
        )

    @graken()
    def _smartAI_(self):
        self._token('Double')
        self._token('{')
        self._singleSmartAI_()
        self.ast['singleSmartAI'] = self.last_node
        self._token('}')

        self.ast._define(
            ['singleSmartAI'],
            []
        )

    @graken()
    def _singleDumbAI_(self):
        self._dumbFormationDef_()
        self.ast['formationDef'] = self.last_node
        self._dumbMovementDef_()
        self.ast['movementDef'] = self.last_node
        self._dumbTargetingDef_()
        self.ast['targetingDef'] = self.last_node

        self.ast._define(
            ['formationDef', 'movementDef', 'targetingDef'],
            []
        )

    @graken()
    def _singleMediumAI_(self):
        self._mediumFormationDef_()
        self.ast['formationDef'] = self.last_node
        self._mediumMovementDef_()
        self.ast['movementDef'] = self.last_node
        self._mediumTargetingDef_()
        self.ast['targetingDef'] = self.last_node

        self.ast._define(
            ['formationDef', 'movementDef', 'targetingDef'],
            []
        )

    @graken()
    def _singleSmartAI_(self):
        self._smartFormationDef_()
        self.ast['formationDef'] = self.last_node
        self._smartMovementDef_()
        self.ast['movementDef'] = self.last_node
        self._smartTargetingDef_()
        self.ast['targetingDef'] = self.last_node

        self.ast._define(
            ['formationDef', 'movementDef', 'targetingDef'],
            []
        )

    @graken()
    def _dumbFormationDef_(self):
        self._token('Formation')
        self._token('{')
        with self._optional():
            self._dumbFormationRules_()
            self.ast['formationRules'] = self.last_node
        self._token('}')

        self.ast._define(
            ['formationRules'],
            []
        )

    @graken()
    def _mediumFormationDef_(self):
        self._token('Formation')
        self._token('{')
        with self._optional():
            self._mediumFormationRules_()
            self.ast['formationRules'] = self.last_node
        self._token('}')

        self.ast._define(
            ['formationRules'],
            []
        )

    @graken()
    def _smartFormationDef_(self):
        self._token('Formation')
        self._token('{')
        with self._optional():
            self._smartFormationRules_()
            self.ast['formationRules'] = self.last_node
        self._token('}')

        self.ast._define(
            ['formationRules'],
            []
        )

    @graken()
    def _dumbMovementDef_(self):
        self._token('Movement')
        self._token('{')
        with self._optional():
            self._dumbMovementRules_()
            self.ast['movementRules'] = self.last_node
        self._token('}')

        self.ast._define(
            ['movementRules'],
            []
        )

    @graken()
    def _mediumMovementDef_(self):
        self._token('Movement')
        self._token('{')
        with self._optional():
            self._mediumMovementRules_()
            self.ast['movementRules'] = self.last_node
        self._token('}')

        self.ast._define(
            ['movementRules'],
            []
        )

    @graken()
    def _smartMovementDef_(self):
        self._token('Movement')
        self._token('{')
        with self._optional():
            self._smartMovementRules_()
            self.ast['movementRules'] = self.last_node
        self._token('}')

        self.ast._define(
            ['movementRules'],
            []
        )

    @graken()
    def _dumbTargetingDef_(self):
        self._token('Targeting')
        self._token('{')
        with self._optional():
            self._dumbTargetingRules_()
            self.ast['targetingRules'] = self.last_node
        self._token('}')

        self.ast._define(
            ['targetingRules'],
            []
        )

    @graken()
    def _mediumTargetingDef_(self):
        self._token('Targeting')
        self._token('{')
        with self._optional():
            self._mediumTargetingRules_()
            self.ast['targetingRules'] = self.last_node
        self._token('}')

        self.ast._define(
            ['targetingRules'],
            []
        )

    @graken()
    def _smartTargetingDef_(self):
        self._token('Targeting')
        self._token('{')
        with self._optional():
            self._smartTargetingRules_()
            self.ast['targetingRules'] = self.last_node
        self._token('}')

        self.ast._define(
            ['targetingRules'],
            []
        )

    @graken()
    def _dumbFormationRules_(self):
        with self._choice():
            with self._option():
                with self._optional():
                    self._extraDumbFormationRules_()
                    self.ast['extraFormationRules'] = self.last_node
                self._token('default:')
                self._dumbFormation_()
                self.ast['defaultFormation'] = self.last_node
            with self._option():
                self._extraDumbFormationRules_()
                self.ast['extraFormationRules'] = self.last_node
            self._error('no available options')

        self.ast._define(
            ['extraFormationRules', 'defaultFormation'],
            []
        )

    @graken()
    def _mediumFormationRules_(self):
        with self._choice():
            with self._option():
                with self._optional():
                    self._extraMediumFormationRules_()
                    self.ast['extraFormationRules'] = self.last_node
                self._token('default:')
                self._mediumFormation_()
                self.ast['defaultFormation'] = self.last_node
            with self._option():
                self._extraMediumFormationRules_()
                self.ast['extraFormationRules'] = self.last_node
            self._error('no available options')

        self.ast._define(
            ['extraFormationRules', 'defaultFormation'],
            []
        )

    @graken()
    def _smartFormationRules_(self):
        with self._choice():
            with self._option():
                with self._optional():
                    self._extraSmartFormationRules_()
                    self.ast['extraFormationRules'] = self.last_node
                self._token('default:')
                self._smartFormation_()
                self.ast['defaultFormation'] = self.last_node
            with self._option():
                self._extraSmartFormationRules_()
                self.ast['extraFormationRules'] = self.last_node
            self._error('no available options')

        self.ast._define(
            ['extraFormationRules', 'defaultFormation'],
            []
        )

    @graken()
    def _dumbMovementRules_(self):
        with self._choice():
            with self._option():
                with self._optional():
                    self._extraDumbMovementRules_()
                    self.ast['extraMovementRules'] = self.last_node
                self._token('default:')
                self._dumbMovement_()
                self.ast['defaultMovement'] = self.last_node
            with self._option():
                self._extraDumbMovementRules_()
                self.ast['extraMovementRules'] = self.last_node
            self._error('no available options')

        self.ast._define(
            ['extraMovementRules', 'defaultMovement'],
            []
        )

    @graken()
    def _mediumMovementRules_(self):
        with self._choice():
            with self._option():
                with self._optional():
                    self._extraMediumMovementRules_()
                    self.ast['extraMovementRules'] = self.last_node
                self._token('default:')
                self._mediumMovement_()
                self.ast['defaultMovement'] = self.last_node
            with self._option():
                self._extraMediumMovementRules_()
                self.ast['extraMovementRules'] = self.last_node
            self._error('no available options')

        self.ast._define(
            ['extraMovementRules', 'defaultMovement'],
            []
        )

    @graken()
    def _smartMovementRules_(self):
        with self._choice():
            with self._option():
                with self._optional():
                    self._extraSmartMovementRules_()
                    self.ast['extraSmartMovementRules'] = self.last_node
                self._token('default:')
                self._smartMovement_()
                self.ast['defaultMovement'] = self.last_node
            with self._option():
                self._extraSmartMovementRules_()
                self.ast['extraMovementRules'] = self.last_node
            self._error('no available options')

        self.ast._define(
            ['extraSmartMovementRules', 'defaultMovement', 'extraMovementRules'],
            []
        )

    @graken()
    def _dumbTargetingRules_(self):
        with self._choice():
            with self._option():
                with self._optional():
                    self._extraDumbTargetingRules_()
                    self.ast['extraTargetingRules'] = self.last_node
                self._token('default:')
                self._dumbTargeting_()
                self.ast['defaultTargeting'] = self.last_node
            with self._option():
                self._extraDumbTargetingRules_()
                self.ast['extraTargetingRules'] = self.last_node
            self._error('no available options')

        self.ast._define(
            ['extraTargetingRules', 'defaultTargeting'],
            []
        )

    @graken()
    def _mediumTargetingRules_(self):
        with self._choice():
            with self._option():
                with self._optional():
                    self._extraMediumTargetingRules_()
                    self.ast['extraTargetingRules'] = self.last_node
                self._token('default:')
                self._mediumTargeting_()
                self.ast['defaultTargeting'] = self.last_node
            with self._option():
                self._extraMediumTargetingRules_()
                self.ast['extraTargetingRules'] = self.last_node
            self._error('no available options')

        self.ast._define(
            ['extraTargetingRules', 'defaultTargeting'],
            []
        )

    @graken()
    def _smartTargetingRules_(self):
        with self._choice():
            with self._option():
                with self._optional():
                    self._extraSmartTargetingRules_()
                    self.ast['extraTargetingRules'] = self.last_node
                self._token('default:')
                self._smartTargeting_()
                self.ast['defaultTargeting'] = self.last_node
            with self._option():
                self._extraSmartTargetingRules_()
                self.ast['extraTargetingRules'] = self.last_node
            self._error('no available options')

        self.ast._define(
            ['extraTargetingRules', 'defaultTargeting'],
            []
        )

    @graken()
    def _extraDumbFormationRules_(self):

        def block0():
            self._dumbFormationRule_()
            self.ast['formationRule'] = self.last_node
        self._positive_closure(block0)

        self.ast._define(
            ['formationRule'],
            []
        )

    @graken()
    def _extraMediumFormationRules_(self):

        def block0():
            self._mediumFormationRule_()
            self.ast['formationRule'] = self.last_node
        self._positive_closure(block0)

        self.ast._define(
            ['formationRule'],
            []
        )

    @graken()
    def _extraSmartFormationRules_(self):

        def block0():
            self._smartFormationRule_()
            self.ast['formationRule'] = self.last_node
        self._positive_closure(block0)

        self.ast._define(
            ['formationRule'],
            []
        )

    @graken()
    def _extraDumbMovementRules_(self):

        def block0():
            self._dumbMovementRule_()
            self.ast['movementRule'] = self.last_node
        self._positive_closure(block0)

        self.ast._define(
            ['movementRule'],
            []
        )

    @graken()
    def _extraMediumMovementRules_(self):

        def block0():
            self._mediumMovementRule_()
            self.ast['movementRule'] = self.last_node
        self._positive_closure(block0)

        self.ast._define(
            ['movementRule'],
            []
        )

    @graken()
    def _extraSmartMovementRules_(self):

        def block0():
            self._smartMovementRule_()
            self.ast['movementRule'] = self.last_node
        self._positive_closure(block0)

        self.ast._define(
            ['movementRule'],
            []
        )

    @graken()
    def _extraDumbTargetingRules_(self):

        def block0():
            self._dumbTargetingRule_()
            self.ast['targetingRule'] = self.last_node
        self._positive_closure(block0)

        self.ast._define(
            ['targetingRule'],
            []
        )

    @graken()
    def _extraMediumTargetingRules_(self):

        def block0():
            self._mediumTargetingRule_()
            self.ast['targetingRule'] = self.last_node
        self._positive_closure(block0)

        self.ast._define(
            ['targetingRule'],
            []
        )

    @graken()
    def _extraSmartTargetingRules_(self):

        def block0():
            self._smartTargetingRule_()
            self.ast['targetingRule'] = self.last_node
        self._positive_closure(block0)

        self.ast._define(
            ['targetingRule'],
            []
        )

    @graken()
    def _dumbFormationRule_(self):
        self._conditional_()
        self.ast['conditional'] = self.last_node
        self._token(':')
        self._dumbFormation_()
        self.ast['formation'] = self.last_node

        self.ast._define(
            ['conditional', 'formation'],
            []
        )

    @graken()
    def _mediumFormationRule_(self):
        self._conditional_()
        self.ast['conditional'] = self.last_node
        self._token(':')
        self._mediumFormation_()
        self.ast['formation'] = self.last_node

        self.ast._define(
            ['conditional', 'formation'],
            []
        )

    @graken()
    def _smartFormationRule_(self):
        self._conditional_()
        self.ast['conditional'] = self.last_node
        self._token(':')
        self._smartFormation_()
        self.ast['formation'] = self.last_node

        self.ast._define(
            ['conditional', 'formation'],
            []
        )

    @graken()
    def _dumbMovementRule_(self):
        self._conditional_()
        self.ast['conditional'] = self.last_node
        self._token(':')
        self._dumbMovement_()
        self.ast['movement'] = self.last_node

        self.ast._define(
            ['conditional', 'movement'],
            []
        )

    @graken()
    def _mediumMovementRule_(self):
        self._conditional_()
        self.ast['conditional'] = self.last_node
        self._token(':')
        self._mediumMovement_()
        self.ast['movement'] = self.last_node

        self.ast._define(
            ['conditional', 'movement'],
            []
        )

    @graken()
    def _smartMovementRule_(self):
        self._conditional_()
        self.ast['conditional'] = self.last_node
        self._token(':')
        self._smartMovement_()
        self.ast['movement'] = self.last_node

        self.ast._define(
            ['conditional', 'movement'],
            []
        )

    @graken()
    def _dumbTargetingRule_(self):
        self._conditional_()
        self.ast['conditional'] = self.last_node
        self._token(':')
        self._dumbTargeting_()
        self.ast['targeting'] = self.last_node

        self.ast._define(
            ['conditional', 'targeting'],
            []
        )

    @graken()
    def _mediumTargetingRule_(self):
        self._conditional_()
        self.ast['conditional'] = self.last_node
        self._token(':')
        self._mediumTargeting_()
        self.ast['targeting'] = self.last_node

        self.ast._define(
            ['conditional', 'targeting'],
            []
        )

    @graken()
    def _smartTargetingRule_(self):
        self._conditional_()
        self.ast['conditional'] = self.last_node
        self._token(':')
        self._smartTargeting_()
        self.ast['targeting'] = self.last_node

        self.ast._define(
            ['conditional', 'targeting'],
            []
        )

    @graken()
    def _dumbFormation_(self):
        self._formation_()
        self.ast['formation'] = self.last_node

        self.ast._define(
            ['formation'],
            []
        )

    @graken()
    def _mediumFormation_(self):
        self._formation_()
        self.ast['formation'] = self.last_node

        self.ast._define(
            ['formation'],
            []
        )

    @graken()
    def _smartFormation_(self):
        self._formation_()
        self.ast['formation'] = self.last_node

        self.ast._define(
            ['formation'],
            []
        )

    @graken()
    def _formation_(self):
        with self._choice():
            with self._option():
                self._token('tight formation')
            with self._option():
                self._token('loose formation')
            with self._option():
                self._token('isolation')
            self._error('expecting one of: isolation loose formation tight formation')

    @graken()
    def _dumbMovement_(self):
        self._movement_()
        self.ast['movement'] = self.last_node

        self.ast._define(
            ['movement'],
            []
        )

    @graken()
    def _mediumMovement_(self):
        self._movement_()
        self.ast['movement'] = self.last_node

        self.ast._define(
            ['movement'],
            []
        )

    @graken()
    def _smartMovement_(self):
        self._movement_()
        self.ast['movement'] = self.last_node

        self.ast._define(
            ['movement'],
            []
        )

    @graken()
    def _movement_(self):
        with self._choice():
            with self._option():
                self._token('move toward')
            with self._option():
                self._token('move away')
            with self._option():
                self._token('hold ground')
            self._error('expecting one of: hold ground move away move toward')

    @graken()
    def _dumbTargeting_(self):
        self._targeting_()
        self.ast['targeting'] = self.last_node

        self.ast._define(
            ['targeting'],
            []
        )

    @graken()
    def _mediumTargeting_(self):
        self._targeting_()
        self.ast['targeting'] = self.last_node

        self.ast._define(
            ['targeting'],
            []
        )

    @graken()
    def _smartTargeting_(self):
        self._targeting_()
        self.ast['targeting'] = self.last_node

        self.ast._define(
            ['targeting'],
            []
        )

    @graken()
    def _targeting_(self):
        with self._choice():
            with self._option():
                self._token('target closest')
            with self._option():
                self._token('target farthest')
            with self._option():
                self._token('target lowest health')
            with self._option():
                self._token('target smartest')
            with self._option():
                self._token('target highest range')
            self._error('expecting one of: target closest target farthest target highest range target lowest health target smartest')

    @graken()
    def _conditional_(self):
        self._token('if')
        self._condition_()
        self.ast['condition'] = self.last_node
        with self._optional():
            self._extraConditions_()

        self.ast._define(
            ['condition'],
            []
        )

    @graken()
    def _extraConditions_(self):
        self._token('and')
        self._condition_()
        self.ast['condition'] = self.last_node
        with self._optional():
            self._extraConditions_()

        self.ast._define(
            ['condition'],
            []
        )

    @graken()
    def _condition_(self):
        with self._choice():
            with self._option():
                self._enemyProximity_()
                self.ast['enemyProximity'] = self.last_node
            with self._option():
                self._allyProximity_()
                self.ast['allyProximity'] = self.last_node
            with self._option():
                self._myHealth_()
                self.ast['myHealth'] = self.last_node
            with self._option():
                self._enemyIQ_()
                self.ast['enemyIQ'] = self.last_node
            with self._option():
                self._enemyHealth_()
                self.ast['enemyHealth'] = self.last_node
            with self._option():
                self._enemyRange_()
                self.ast['enemyRange'] = self.last_node
            self._error('no available options')

        self.ast._define(
            ['enemyProximity', 'allyProximity', 'myHealth', 'enemyIQ', 'enemyHealth', 'enemyRange'],
            []
        )

    @graken()
    def _enemyProximity_(self):
        self._token('there are')
        self._number_()
        self.ast['number'] = self.last_node
        self._token('enemies')
        self._proximity_()
        self.ast['proximity'] = self.last_node

        self.ast._define(
            ['number', 'proximity'],
            []
        )

    @graken()
    def _allyProximity_(self):
        self._token('there are')
        self._number_()
        self.ast['number'] = self.last_node
        self._token('allies')
        self._proximity_()
        self.ast['proximity'] = self.last_node

        self.ast._define(
            ['number', 'proximity'],
            []
        )

    @graken()
    def _proximity_(self):
        with self._choice():
            with self._option():
                self._token('adjacent')
            with self._option():
                self._token('close')
            with self._option():
                self._token('around')
            self._error('expecting one of: adjacent around close')

    @graken()
    def _myHealth_(self):
        self._token('health')
        self._comparison_()
        self.ast['comparison'] = self.last_node
        self._number_()
        self.ast['number'] = self.last_node

        self.ast._define(
            ['comparison', 'number'],
            []
        )

    @graken()
    def _enemyIQ_(self):
        self._token('a nearby enemy has IQ')
        self._comparison_()
        self.ast['comparison'] = self.last_node
        self._number_()
        self.ast['number'] = self.last_node

        self.ast._define(
            ['comparison', 'number'],
            []
        )

    @graken()
    def _enemyHealth_(self):
        self._token('a nearby enemy has health')
        self._comparison_()
        self.ast['comparison'] = self.last_node
        self._number_()
        self.ast['number'] = self.last_node

        self.ast._define(
            ['comparison', 'number'],
            []
        )

    @graken()
    def _enemyRange_(self):
        self._token('a nearby enemy has range')
        self._comparison_()
        self.ast['comparison'] = self.last_node
        self._number_()
        self.ast['number'] = self.last_node

        self.ast._define(
            ['comparison', 'number'],
            []
        )

    @graken()
    def _comparison_(self):
        with self._choice():
            with self._option():
                self._token('<')
            with self._option():
                self._token('>')
            self._error('expecting one of: < >')

    @graken()
    def _number_(self):
        self._pattern(r'[0-9]+')


class SingleAIGrammarSemantics(object):
    def allAIs(self, ast):
        return ast

    def dumbAI(self, ast):
        return ast

    def mediumAI(self, ast):
        return ast

    def smartAI(self, ast):
        return ast

    def singleDumbAI(self, ast):
        return ast

    def singleMediumAI(self, ast):
        return ast

    def singleSmartAI(self, ast):
        return ast

    def dumbFormationDef(self, ast):
        return ast

    def mediumFormationDef(self, ast):
        return ast

    def smartFormationDef(self, ast):
        return ast

    def dumbMovementDef(self, ast):
        return ast

    def mediumMovementDef(self, ast):
        return ast

    def smartMovementDef(self, ast):
        return ast

    def dumbTargetingDef(self, ast):
        return ast

    def mediumTargetingDef(self, ast):
        return ast

    def smartTargetingDef(self, ast):
        return ast

    def dumbFormationRules(self, ast):
        return ast

    def mediumFormationRules(self, ast):
        return ast

    def smartFormationRules(self, ast):
        return ast

    def dumbMovementRules(self, ast):
        return ast

    def mediumMovementRules(self, ast):
        return ast

    def smartMovementRules(self, ast):
        return ast

    def dumbTargetingRules(self, ast):
        return ast

    def mediumTargetingRules(self, ast):
        return ast

    def smartTargetingRules(self, ast):
        return ast

    def extraDumbFormationRules(self, ast):
        return ast

    def extraMediumFormationRules(self, ast):
        return ast

    def extraSmartFormationRules(self, ast):
        return ast

    def extraDumbMovementRules(self, ast):
        return ast

    def extraMediumMovementRules(self, ast):
        return ast

    def extraSmartMovementRules(self, ast):
        return ast

    def extraDumbTargetingRules(self, ast):
        return ast

    def extraMediumTargetingRules(self, ast):
        return ast

    def extraSmartTargetingRules(self, ast):
        return ast

    def dumbFormationRule(self, ast):
        return ast

    def mediumFormationRule(self, ast):
        return ast

    def smartFormationRule(self, ast):
        return ast

    def dumbMovementRule(self, ast):
        return ast

    def mediumMovementRule(self, ast):
        return ast

    def smartMovementRule(self, ast):
        return ast

    def dumbTargetingRule(self, ast):
        return ast

    def mediumTargetingRule(self, ast):
        return ast

    def smartTargetingRule(self, ast):
        return ast

    def dumbFormation(self, ast):
        return ast

    def mediumFormation(self, ast):
        return ast

    def smartFormation(self, ast):
        return ast

    def formation(self, ast):
        return ast

    def dumbMovement(self, ast):
        return ast

    def mediumMovement(self, ast):
        return ast

    def smartMovement(self, ast):
        return ast

    def movement(self, ast):
        return ast

    def dumbTargeting(self, ast):
        return ast

    def mediumTargeting(self, ast):
        return ast

    def smartTargeting(self, ast):
        return ast

    def targeting(self, ast):
        return ast

    def conditional(self, ast):
        return ast

    def extraConditions(self, ast):
        return ast

    def condition(self, ast):
        return ast

    def enemyProximity(self, ast):
        return ast

    def allyProximity(self, ast):
        return ast

    def proximity(self, ast):
        return ast

    def myHealth(self, ast):
        return ast

    def enemyIQ(self, ast):
        return ast

    def enemyHealth(self, ast):
        return ast

    def enemyRange(self, ast):
        return ast

    def comparison(self, ast):
        return ast

    def number(self, ast):
        return ast


def main(filename, startrule, trace=False, whitespace=None, nameguard=None):
    import json
    with open(filename) as f:
        text = f.read()
    parser = SingleAIGrammarParser(parseinfo=False)
    ast = parser.parse(
        text,
        startrule,
        filename=filename,
        trace=trace,
        whitespace=whitespace,
        nameguard=nameguard)
    print('AST:')
    print(ast)
    print()
    print('JSON:')
    print(json.dumps(ast, indent=2))
    print()

if __name__ == '__main__':
    import argparse
    import string
    import sys

    class ListRules(argparse.Action):
        def __call__(self, parser, namespace, values, option_string):
            print('Rules:')
            for r in SingleAIGrammarParser.rule_list():
                print(r)
            print()
            sys.exit(0)

    parser = argparse.ArgumentParser(description="Simple parser for SingleAIGrammar.")
    parser.add_argument('-l', '--list', action=ListRules, nargs=0,
                        help="list all rules and exit")
    parser.add_argument('-n', '--no-nameguard', action='store_true',
                        dest='no_nameguard',
                        help="disable the 'nameguard' feature")
    parser.add_argument('-t', '--trace', action='store_true',
                        help="output trace information")
    parser.add_argument('-w', '--whitespace', type=str, default=string.whitespace,
                        help="whitespace specification")
    parser.add_argument('file', metavar="FILE", help="the input file to parse")
    parser.add_argument('startrule', metavar="STARTRULE",
                        help="the start rule for parsing")
    args = parser.parse_args()

    main(
        args.file,
        args.startrule,
        trace=args.trace,
        whitespace=args.whitespace,
        nameguard=not args.no_nameguard
    )
